# Generated by Django 2.2.1 on 2019-05-20 19:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasDisponiveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispDia', models.CharField(choices=[('td', 'Todos os dias'), ('ss', 'De segunda a sexta'), ('fs', 'Finais de semana'), ('se', 'Segundas-feiras'), ('te', 'Terças-feiras'), ('qa', 'Quartas-feiras'), ('qi', 'Quintas-feiras'), ('sx', 'Sextas-feiras'), ('sa', 'Sábados'), ('dm', 'Domingos')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('capa', models.ImageField(null=True, upload_to='capaJogos/')),
            ],
        ),
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('p4', 'Playstation 4'), ('p3', 'Playstation 3'), ('xo', 'Xbox One'), ('x3', 'Xbox 360'), ('pc', 'PC'), ('mo', 'Mobile'), ('ns', 'Nintendo Switch'), ('nd', 'Nintendo 3DS')], default='Plataforma', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UsrIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=5)),
                ('iconOptions', models.ImageField(upload_to='iconesUsr/')),
            ],
        ),
        migrations.CreateModel(
            name='UsrPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('horario', models.DateTimeField(default=0)),
                ('comentario', models.TextField(max_length=250)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonday.Jogos')),
                ('plataforma', models.ForeignKey(default='Selecione a Plataforma', on_delete=django.db.models.deletion.CASCADE, to='demonday.Plataformas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeR', models.CharField(blank=True, max_length=40)),
                ('iniHora', models.TimeField(blank=True, default=0)),
                ('fimHora', models.TimeField(blank=True, default=0)),
                ('bio', models.TextField(max_length=300)),
                ('discord', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, default=0, max_length=11, validators=[django.core.validators.RegexValidator(message='Numero de celular deve conter apenas números.', regex='^\\+?1?\\d{9,11}$')])),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('dispDia', models.ManyToManyField(to='demonday.DiasDisponiveis')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonday.UsrIcon')),
                ('jogos', models.ManyToManyField(to='demonday.Jogos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jogos',
            name='plataformas',
            field=models.ManyToManyField(to='demonday.Plataformas'),
        ),
    ]
