# Generated by Django 2.2.1 on 2019-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('p4', 'Playstation 4'), ('p3', 'Playstation 3'), ('xo', 'Xbox One'), ('x3', 'Xbox 360'), ('pc', 'PC'), ('mo', 'Mobile'), ('ns', 'Nintendo Switch'), ('nd', 'Nintendo 3DS')], default='Plataforma', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('capa', models.ImageField(null=True, upload_to='')),
                ('plataforma', models.ManyToManyField(to='demonday.Plataformas')),
            ],
        ),
    ]
