# Generated by Django 2.2.1 on 2019-05-20 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Numero de celular deve conter apenas números.', regex='^\\+?1?\\d{9,11}$')]),
        ),
    ]
