# Generated by Django 2.2.1 on 2019-05-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsrIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=5)),
                ('iconOptions', models.ImageField(upload_to='iconesUsr/')),
            ],
        ),
        migrations.AlterField(
            model_name='jogos',
            name='capa',
            field=models.ImageField(null=True, upload_to='capaJogos/'),
        ),
    ]
