# Generated by Django 2.2.1 on 2019-05-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0002_auto_20190515_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasDisponiveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispDia', models.CharField(choices=[('se', 'Segunda-feiras'), ('te', 'Terça-feiras'), ('qa', 'Quarta-feiras'), ('qi', 'Quinta-feiras'), ('sx', 'Sexta-feiras'), ('sa', 'Sábados'), ('dm', 'Domingos')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispDia', models.ManyToManyField(to='demonday.DiasDisponiveis')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonday.UsrIcon')),
                ('jogos', models.ManyToManyField(to='demonday.Jogos')),
            ],
        ),
    ]
