# Generated by Django 2.2.1 on 2019-05-20 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0002_auto_20190520_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, default=0, max_length=11, validators=[django.core.validators.RegexValidator(message='Numero de celular deve conter apenas números.', regex='^\\+?1?\\d{9,11}$')]),
        ),
        migrations.AlterField(
            model_name='usrposts',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonday.Plataformas'),
        ),
    ]
