# Generated by Django 2.2.1 on 2019-05-17 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demonday', '0003_diasdisponiveis_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=300)),
                ('dispDia', models.ManyToManyField(to='demonday.DiasDisponiveis')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonday.UsrIcon')),
                ('jogos', models.ManyToManyField(to='demonday.Jogos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
