# Generated by Django 2.2.1 on 2019-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0004_auto_20190520_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasdisponiveis',
            name='dispDia',
            field=models.IntegerField(choices=[(1, 'Todos os dias'), (2, 'De segunda a sexta'), (3, 'Finais de semana'), (4, 'Segundas-feiras'), (5, 'Terças-feiras'), (6, 'Quartas-feiras'), (7, 'Quintas-feiras'), (8, 'Sextas-feiras'), (9, 'Sábados'), (10, 'Domingos')]),
        ),
    ]
