# Generated by Django 2.2.1 on 2019-05-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0004_auto_20190517_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nomeR',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
