# Generated by Django 2.2.1 on 2019-05-17 22:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demonday', '0005_perfil_nomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogos',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='jogos',
            name='plataformas',
            field=models.ManyToManyField(to='demonday.Plataformas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='discord',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.CreateModel(
            name='UsrPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('horario', models.DateTimeField()),
                ('comentario', models.TextField(max_length=250)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonday.Jogos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
