# Generated by Django 2.2.1 on 2019-05-20 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0006_auto_20190517_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp',
            field=models.IntegerField(blank=True, default=900, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
    ]
