# Generated by Django 2.2.1 on 2019-05-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0007_auto_20190519_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasdisponiveis',
            name='dispDia',
            field=models.CharField(choices=[('td', 'Todos os dias'), ('ss', 'De segunda a sexta'), ('fs', 'Finais de semana'), ('se', 'Segundas-feiras'), ('te', 'Terças-feiras'), ('qa', 'Quartas-feiras'), ('qi', 'Quintas-feiras'), ('sx', 'Sextas-feiras'), ('sa', 'Sábados'), ('dm', 'Domingos')], max_length=2),
        ),
    ]
