# Generated by Django 2.2.1 on 2019-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0008_auto_20190520_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dispHora',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
