# Generated by Django 2.2.1 on 2019-05-21 17:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0008_auto_20190521_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='jogos',
        ),
        migrations.AddField(
            model_name='perfil',
            name='jogos',
            field=multiselectfield.db.fields.MultiSelectField(default='', max_length=200),
        ),
    ]
