# Generated by Django 2.2.1 on 2019-05-21 18:01

import demonday.models
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0009_auto_20190521_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='jogos',
            field=multiselectfield.db.fields.MultiSelectField(default='', max_length=200, verbose_name=demonday.models.Jogos),
        ),
    ]
