# Generated by Django 2.2.1 on 2019-05-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0009_perfil_disphora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dispHora',
            field=models.TimeField(blank=True, default=''),
        ),
    ]
