# Generated by Django 2.2.1 on 2019-05-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0010_auto_20190521_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='jogos',
        ),
        migrations.AddField(
            model_name='perfil',
            name='jogos',
            field=models.ManyToManyField(to='demonday.Jogos'),
        ),
    ]
