# Generated by Django 2.2.1 on 2019-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0012_openinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='company_logos')),
            ],
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekday',
            field=models.IntegerField(choices=[('td', 'Todos os dias'), ('ss', 'De segunda a sexta'), ('fs', 'Finais de semana'), ('se', 'Segundas-feiras'), ('te', 'Terças-feiras'), ('qa', 'Quartas-feiras'), ('qi', 'Quintas-feiras'), ('sx', 'Sextas-feiras'), ('sa', 'Sábados'), ('dm', 'Domingos')], unique=True),
        ),
    ]
