# Generated by Django 2.2.1 on 2019-05-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0013_auto_20190520_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
