# Generated by Django 2.2.1 on 2019-05-20 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonday', '0014_auto_20190520_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,11}$')]),
        ),
    ]
